project2/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'interview/index', to: 'interview#index'
  get 'interview/filter', to: 'interview#filter'
  get 'interview/display_results', to: 'interview#display_results'

  # Redirect the root URL to interview#index with the "type" parameter set to "phyto"
  root to: 'interview#filter_view'
end

project2/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

project2/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

project2/app/controllers/interview_controller.rb
require 'net/http'

class InterviewController < ApplicationController
  def index
    url = 'https://api.omens.com.br/single-item/open'
    response = Net::HTTP.get(URI(url))
    programs = JSON.parse(response)

    programs = programs.select { |program| program['type'] == program_type } if program_type.present?

    output = programs.map do |program|
      program.slice('name', 'price', 'variantId', 'type')
    end

    render json: output, content_type: 'application/json'
  end

  def filter_view; end

  def display_results; end

  private

  def program_type
    return false if params[:type] == 'all'

    params[:type]
  end
end

project2/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

project2/app/helpers/interview_helper.rb
# frozen_string_literal: true

module InterviewHelper
end

project2/app/views/interview/display_results.html.erb
<div class="container">
  <div class="row">
    <div class="d-grid gap-2 d-md-block">
      <button id="toggle-format" type="button" class="btn btn-outline-secondary">Format</button>
      <%= link_to "Filter Again", '#', id: "back-to-filter", class: "btn btn-outline-secondary mt-3" %>
    </div>
    <pre id="json-results"></pre>
  </div>
</div>

<%= javascript_include_tag 'display_results' %>

project2/app/views/interview/filter_view.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center custom-row">
    <div class="col-md-6 text-center">
    <h1 id="main-header" class="mb-3">Filter Your Result By Type</h1>
      <%= form_tag interview_index_path, method: :get do %>
        <div class="filter-wrapper">
          <%= select_tag :type, options_for_select([['All', 'all'], ['Course', 'course'], ['Phyto', 'phyto'], ['Psycho', 'psycho']]), prompt: "Filters", class: "form-select" %>
        </div>
        <%= submit_tag 'Filter', class: 'btn btn-primary mt-3' %>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'filter' %>

project2/app/views/interview/index.html.erb
<%= javascript_include_tag 'filter' %>

project2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>